### ISSUE TITLE
QT4W_demo_project调试时，无法使用chrome浏览器打开URL

### ISSUE THREAD

**Issue by Brown-229** [qtacore/QT4C#12]
F:\QTA\QT4WDemoProj-master>python manage.py runscript webdemotest/hello.py
============================================================
测试用例:WebDemoTest 所有者:qta 优先级:High 超时:5分钟
============================================================
----------------------------------------
步骤1: 1. 在浏览器中打开测试页面
2020-03-03 11:02:45,152 2260 [Browser] Browser ChromeBrowser not implement clear_data method
CRITICAL: run_test执行失败
Traceback (most recent call last):
  File "D:\python3\lib\site-packages\browser\chrome.py", line 125, in get_browser_path
    hkey = winreg.OpenKey(winreg.HKEY_LOCAL_MACHINE, sub_key)
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\python3\lib\site-packages\browser\chrome.py", line 130, in get_browser_path
    hkey = winreg.OpenKey(winreg.HKEY_CURRENT_USER, sub_key)
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

**Comment by Ming5024** [comment]
已经在 #13 中对chrome.exe增加了环境变量及常用安装目录的查找
